reference-db:
  "Host": "192.168.8.143"
  "Port": 3306
  "Username": "username"
  "Password": "pass"
  "Database": "refdb"
queue-db:
  "Host": "192.168.8.143"
  "Port": 6379
  "Username": ""
  "Password": ""
  "MasterName": ""
  "Addresses": []
  "Database": 0
  "PoolSize": 10
transaction-db:
  "Host": "192.168.8.143"
  "Port": 18002
  "Username": "username"
  "Password": "pass"
  "Database": "tr_db"
  "DialTimeout": 10
  "MaxOpenConns": 100
  "MaxIdleConns": 100